apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  annotations:
    kaoto.io/description: ""
  name: kafka-consumer
spec:
  source:
    properties:
      password: kafkauser1
      securityProtocol: SASL_PLAINTEXT
      bootstrapServers: my-cluster-kafka-bootstrap:9092
      topic: a_requests
      user: consumer
      consumerGroup: a_group
      autoOffsetReset: earliest
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: kafka-scram-source
    types: {}
  sink:
    properties:
      level: info
      multiline: "true"
      showAllProperties: "true"
      loggerName: DemoKafka
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
    types: {}
