apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  annotations:
    kaoto.io/description: ""
  name: kafka-producer 
spec:
  source:
    properties:
      period: 2000
      message: Test
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
    types: {}
  sink:
    properties:
      password: kafkauser1
      securityProtocol: SASL_PLAINTEXT
      bootstrapServers: my-cluster-kafka-bootstrap:9092
      topic: a_requests
      saslMechanism: SCRAM-SHA-512
      user: producer
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: kafka-scram-sink
    types: {}