apiVersion: v1
data:
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

      <proxies></proxies>
      <profiles>
        <profile>
          <id>maven-main</id>
          <repositories>
            <repository>
                <id>apache</id>
                <url>https://repository.apache.org/content/groups/snapshots</url>
                <releases>
                  <enabled>false</enabled>
                </releases>
                <snapshots>
                  <enabled>true</enabled>
                </snapshots>
              </repository>
            <repository>
                <id>jboss-ga</id>
                <url>https://maven.repository.redhat.com/ga</url>
                <releases>
                  <enabled>true</enabled>
                </releases>
                <snapshots>
                  <enabled>true</enabled>
                </snapshots>
              </repository>
            <repository>
              <id>maven-central</id>
              <url>https://repo1.maven.org/maven2/</url>
                <releases>
                  <enabled>true</enabled>
                </releases>
              <snapshots>
                  <enabled>true</enabled>
              </snapshots>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <id>maven-central</id>
              <url>https://repo1.maven.org/maven2/</url>
              <releases />
              <snapshots>
                  <enabled>true</enabled>
              </snapshots>
            </pluginRepository>
            <pluginRepository>
              <id>jboss-ga-plugin-repository</id>
              <url>https://maven.repository.redhat.com/ga</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </pluginRepository>
          </pluginRepositories>
        </profile>
      </profiles>

      <activeProfiles>
        <activeProfile>maven-main</activeProfile>
      </activeProfiles>

    </settings>
kind: ConfigMap
metadata:
  name: maven-settings
