- name: Evaluate Instance Config
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - topic_request.yml
    - secret_users_password.yml
    - user_consumer.yml
    - user_producer.yml
    - user_kafka-ui.yml
