apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: consumer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: kafka-clients-password
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: a_requests
          patternType: literal
        operations: 
          - Read
          - Describe
        host: "*"
      - resource:
          type: group
          name: a_group
          patternType: literal
        operations: 
          - Read
        host: "*"
