- hosts: localhost
  name: Install AMQ Streams + Camel K Demo
  vars:
    cluster_project: demo-camelk-kafka
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    verify_tls: false
    delete_demo: false
    camel_k_name: camel-k
    camel_k_channel: stable-2.0
    camel_k_source: community-operators
    # camel_k_name: red-hat-camel-k
    # camel_k_channel: 1.10.x
    # camel_k_source: redhat-operators
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This playbook requires 'server' and 'token' to be defined"
      when:
        - (server is undefined) or (token is undefined) or (server | length == 0) or (token | length == 0)
      ignore_errors: false

    - name: Define domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Include AMQ Streams role
      ansible.builtin.include_role:
        name: streams

    - name: Include Monitoring role
      ansible.builtin.include_role:
        name: monitoring

    - name: Include kafka-ui role
      ansible.builtin.include_role:
        name: kafka-ui

    - name: Include Camel K role
      ansible.builtin.include_role:
        name: camel-k
